export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_ERROR = 'USER_DETAILS_ERROR';

export const SEND_PASSWORD_DETAILS_REQUEST = 'SEND_PASSWORD_DETAILS_REQUEST';
export const SEND_PASSWORD_DETAILS_SUCCESS = 'SEND_PASSWORD_DETAILS_SUCCESS';
export const SEND_PASSWORD_DETAILS_ERROR = 'SEND_PASSWORD_DETAILS_ERROR';

export const PRODUCT_TYPE_DETAILS_REQUEST = 'PRODUCT_TYPE_DETAILS_REQUEST';
export const PRODUCT_TYPE_DETAILS_SUCCESS = 'PRODUCT_TYPE_DETAILS_SUCCESS';
export const PRODUCT_TYPE_DETAILS_ERROR = 'PRODUCT_TYPE_DETAILS_ERROR';

export const INSERT_PRODUCT_DETAILS_REQUEST = 'INSERT_PRODUCT_DETAILS_REQUEST';
export const INSERT_PRODUCT_DETAILS_SUCCESS = 'INSERT_PRODUCT_DETAILS_SUCCESS';
export const INSERT_PRODUCT_DETAILS_ERROR = 'INSERT_PRODUCT_DETAILS_ERROR';

export const DISPLAY_PRODUCT_DETAILS_REQUEST = 'DISPLAY_PRODUCT_DETAILS_REQUEST';
export const DISPLAY_PRODUCT_DETAILS_SUCCESS = 'DISPLAY_PRODUCT_DETAILS_SUCCESS';
export const DISPLAY_PRODUCT_DETAILS_ERROR = 'DISPLAY_PRODUCT_DETAILS_ERROR';
