export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_ERROR = 'USER_DETAILS_ERROR';

export const SEND_PASSWORD_DETAILS_REQUEST = 'SEND_PASSWORD_DETAILS_REQUEST';
export const SEND_PASSWORD_DETAILS_SUCCESS = 'SEND_PASSWORD_DETAILS_SUCCESS';
export const SEND_PASSWORD_DETAILS_ERROR = 'SEND_PASSWORD_DETAILS_ERROR';
